### ISSUE TITLE
Variable conv_featuresbatch_norm/beta/RMSProp/ does not exist

### ISSUE THREAD

**Issue by YanceyZhangDL** [yunjey/show-attend-and-tell#21]
hey, I encountered a problem when i run python train.py. The full error is
ValueError: Variable conv_featuresbatch_norm/beta/RMSProp/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

occured in this line(87):  train_op = optimizer.apply_gradients(grads_and_vars=grads_and_vars)

**Comment by YanceyZhangDL** [comment]
I fix the problem myself. it's about the variable sharing mechanism.

**Comment by nsknsl** [comment]
I came across the same problem. Can you explain how you fix this in more details? Thank you.

**Comment by YanceyZhangDL** [comment]
@nsknsl I sugget you see the tensorflow tutorial to see the variable sharing mechanism to fix these problems then you can get the answer.
