### ISSUE TITLE
how to fix train.py on tensorflow1.0

### ISSUE THREAD

**Issue by lijianqing317** [yunjey/show-attend-and-tell#23]
when i run train.py ,i can't find rnn_cell,then i use tf.contrib.rnn instead. Being given TypeError: Expected int32, got list containing Tensors of type '_Message' instead.I dont' know how to fix

**Comment by lijianqing317** [comment]
After reading the code to adjust the code have been resolved

**Comment by lijianqing317** [comment]
After reading the code to adjust the code have been resolved

**Comment by gaterw** [comment]
sorry to disturb. but i wonder how you adjust the code in the tensorflow1.0 
thanks a lot.

**Comment by lijianqing317** [comment]
[Here](https://github.com/lijianqing317/showandtell10) I just upload I changed part of the code, and you can run it with 1.0, I'd already run it on my computer,

**Comment by gaterw** [comment]
thanks a lot, it does help. thank u.
