### ISSUE TITLE
Bleu result

### ISSUE THREAD

**Issue by arieling** [yunjey/show-attend-and-tell#25]
In the paper, their Bleu-1 result is 70.7 in the end.
I trained this model and final bleu score is about 66.5.
Do you have the same behaviour?  What could be the problem?

**Comment by anantsubramanian** [comment]
Hey,

Did you manage to figure out why the values are different? Are the hyperparameters used different from the ones used in the original paper/code?

For instance, the maximum caption length used by the original authors is 30, whereas this code uses 16. Could this be the reason for the difference?
