### ISSUE TITLE
Problem in evaluate_model.ipynb

### ISSUE THREAD

**Issue by xinxin321** [yunjey/show-attend-and-tell#36]
When i run the evaluate_model.ipynb,it just show that: 
InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1500] rhs shape= [1024]
	 [[Node: save/Assign_8 = Assign[T=DT_FLOAT, _class=["loc:@initial_lstm/b_h"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](initial_lstm/b_h, save/restore_slice_8/_33)]]
	 [[Node: save/restore_slice_15/_4 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_7_save/restore_slice_15", _device="/job:localhost/replica:0/task:0/cpu:0"](save/restore_slice_15)]]

**Comment by JaneLou** [comment]
you probably should change `dim_hidden=1500`  to  `dim_hidden=1024` which is the same size as training

**Comment by xinxin321** [comment]
Thank you .And i change it ,and ti works.Tanks!

**Comment by preetskhalsa97** [comment]
I had the same error. However, after making the change, I got the following error:

ValueError: Trying to share variable initial_lstm/w_h, but specified shape (512, 1024) and found shape (512, 1500).

@xinxin321 can you please help me out? Thanks! :)
