### ISSUE TITLE
about prev2out and evaluation score

### ISSUE THREAD

**Issue by DongNaeSwellfish** [yunjey/show-attend-and-tell#39]
Does the prev2out make big difference in evaluation?
Does anyone had tried this and have evaluation score of this

**Comment by yunjey** [comment]
@DongNaeSwellfish No, it does not effect the performance of the model.

**Comment by DongNaeSwellfish** [comment]
Thanks! I was reproducing the show attend and tell in pytorch and couldn't get the evaluation score same as the paper, so wondered if this problem matters much...

**Comment by yunjey** [comment]
@DongNaeSwellfish If you use pretrained `resnet152` instead of `vggnet`, then the performance of the model will be hugely increased. Good luck!

**Comment by clever-curl-curl** [comment]
@yunjey  Thanks for your code! If I use resnet152, image feature will be [2048], an one-dimension vector. So it will lose spatial information and can I still attention to it?

**Comment by clever-curl-curl** [comment]
Because I use [2048]dimensions of resnet, the result get worse...

**Comment by alexandercameronh** [comment]
@clever-curl-curl did you end up using a different CNN architecture to produce better results? If so, please let me know which pre-trained architecture you used and if you were still able to apply attention. Thanks!!

**Comment by saruvora** [comment]
@clever-curl-curl hi can you please share your code for resnet-152 or resnet-50 ?
